- http.ts
I think
`response.contents.find(content =>)`
reads better than
`response.content.find(content =>)`
> chore(IHttpResponse): 'content' to 'contents'

- http.ts
I believe `deprecated: object` was there by mistake.
> Changed IHttpParam.deprecated type to boolean

- src/http-spec.ts
- src/servers.ts
We originally wanted version in data for nodes requiring this version properties to be added. We have since changed directions and no longer need these props.
> fix: remove version from types [SD-438]

- src/http-spec.ts
BREAKING CHANGE: `IHttpParam.contents` renamed to `IHttpParam.content`, and is an object now instead of an array.
> feat: split IHttpContent and IMediaTypeContent

- package.json
- src/basic.ts
- tsconfig.build.json
- yarn.lock
1. Update to TS 3.5
2. Removes `Omit` (it's now included in TS)
3. Provides CommonJS in case somebody (me) wants to use TSC instead of Rollup
4. Updates types
This is a breaking change
> Update to TS 3.5

- src/http-spec.ts
Unfortunately another breaking change. Since params extends the content, the `content` property is not required anymore.
> refactor: remove content

- src/index.ts
Didn't realize everything needs to be exported from index 😬 
Otherwise you're forced to do `import { NodeType } from '@stoplight/types/dist/node';`
> fix: export node ts

- src/parsers.ts
> fix(parser-result): include missed metadata

- .circleci/config.yml
- package.json
- src/http-spec.ts
- yarn.lock
This PR adds the `CommaLimited` parameter type that is allowed in OpenAPI 2.0 documents and can be used in the body (when type is `formData`).
This will then be released in HttpSpec to correctly transform the value and then propagated again in Prism to handle the parameter type correctly.
> feat: enable comma limited parameters

- src/http.ts
Trace is in OAS3 spec so it's so common that it makes sense to have it in the regular `HttpMethods`
> fix: put trace in common verbs

- src/http-spec.ts
Introduces an IHttpOperation extension called IHttpCallbackOperation. The new interface carries additionally the name of callback operation.
The motivation behind extending the interface: callbacks in OASv3 spec are wrapped in an object with callback name as property and operation as value. SL's way of representing such objects is to convert it to an array and add a property inside with the key name (see operations array, examples array, etc.). This change is compatible with that approach.
**Related PR**: https://github.com/stoplightio/prism/pull/716
**Related issue**: https://github.com/stoplightio/prism/issues/331
**The spec**: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#callbackObject
**Callback example**: …
> feat: callbacks support

- src/http-spec.ts
It turns out Prism has full support for digest scheme when auth type is basic. I am working on some "type-safe" things into it and I discovered this case was not covered at all. This PR fixes it.
> feat: add digest to basic security scheme

- package.json
- src/http-spec.ts
- src/logs.ts
- yarn.lock
This is a battle I am not interested in fighting anymore, so we can remove such constraint so you can remove the casts in http-spec and the other libraries.
> fix: remove the constrains in the response

- src/http-spec.ts
This is a part of making https://github.com/stoplightio/elements/issues/706 possible. The next step will be updating `http-spec`
> feat: add logo support

- src/http-spec.ts
Addresses: https://github.com/stoplightio/platform-internal/issues/7772
Adding `extensions` property to HttpOperation containing all `x-extensions` from the API document operation.
> feat: http operation extensions

- .circleci/config.yml
- package.json
- rollup.config.js
- src/graph.ts
- src/http-spec.ts
- src/http.ts
- src/servers.ts
- tsconfig.json
- yarn.lock
BREAKING CHANGE: id property is required on certain nodes
BREAKING CHANGE: dropped EOL versions of Node.js
> beta -> master

- src/graph.ts
- src/http-spec.ts
I tested it out with Elements, Prism and Platform-internal, and they're all good besides Elements and platform-internal which has around 4-5 errors due to https://github.com/stoplightio/types/commit/650e2b4d4844f3f20eed1b6a6f53701e8294937b
> feat(http-spec): add IBundledHttpService

- src/http-spec.ts
A catch-all bucket for request parameters that we cannot resolve during the transformation to http-spec. Currently we throw these parameters away completely, which is lossy. The main use case is parameters that are a root $ref, which means we cannot infer what type of parameter it is without following the ref, which is not always possible at transformation time.
> feat: add the unknown param type

- src/http-spec.ts
BREAKING CHANGE: IHttpService['security'] is a 2D array now
> feat(http-spec): align IHttpService['security'] with IHttpOperation['security']

- src/node.ts
Adds missing `NodeType.HttpWebhook` enum value
> fix: missing webhook node type
