http.d.ts
- add HttpParamStyles enum
- add style to IHttpParam as optional parameter
- type style on IHttpEncoding
=> Http Param Style Types

http.d.ts
**Summary**
- some minor pluralization and fields rename
=> SL-248: types adjustments

http.d.ts
BREAKING CHANGE: interface name has changed
SL-248
Was requested in https://github.com/stoplightio/graph/pull/16
=> SL-248 feat(http): rename IHttpRequest to IHttpRequestParams

.circleci/config.yml
=> ci(need to build before releasing): duh!

src/http-spec.ts
=> [SL-816] Add IHttpService node

src/parsers.ts
Related: https://github.com/stoplightio/json/pull/18
=> feat: relaxed mode for GetLocationForJsonPath

src/http-spec.ts
This is probably another breaking change :(
=> fix: security is a dictonary

package.json, src/http-spec.ts, src/index.ts, src/schemas.ts, yarn.lock
1. Moves the description in the JSON Schema
2. Removes the `ISchema` interface in favour of regular JSONSchema
=> JSON Schema Normalisation

src/node.ts
- Are any of the types from graph.ts still being used? https://github.com/stoplightio/types/blob/master/src/graph.ts
- Are there any other node types that should be added here?
=> feat: add analyzer node types

src/parsers.ts
This is technically a breaking change :/ driven by https://github.com/stoplightio/yaml/pull/20
Needed by https://github.com/stoplightio/yaml/pull/20/files#diff-9996bd9c42bf84cb5c9e3352d5b20d5eR7
Note - we might close this PR if you think we should be merging keys by default.
=> feat: add metadata property to IParserASTResult

src/http-spec.ts
* Add key property to ISecurityScheme interface
=> feat: add key to ISecurityScheme

src/node.ts
required for https://github.com/stoplightio/platform-internal/issues/1464
=> feat: add raw node type so we can store it in db

src/node.ts
Issue: https://github.com/stoplightio/platform-internal/issues/3211
- Adds node type for table of contents node
=> feat: add table of contents node type

src/http-spec.ts
For https://github.com/stoplightio/platform-internal/issues/5776
=> feat(oas): add license identifier & mutualTLS

src/http-spec.ts
Needed by https://github.com/stoplightio/http-spec/pull/139
=> feat(http-spec): use JSONSchema7

src/node.ts
For https://github.com/stoplightio/platform-internal/issues/6060
=> feat(node): add SpectralRuleset node type

src/http-spec.ts
For https://github.com/stoplightio/platform-internal/issues/6090
=> feat(http-spec): add internal member to IHttpOperation

package.json, rollup.config.js, tsconfig.json, yarn.lock
@marbemac I think we could release a beta version just to make sure it works nicely with everything.
Thoughts?
=> feat: setup dual-packaging

src/node.ts
For stoplightio/platform-internal#9519
The idea is to use this Spec for `styleguide.json` file
=> feat: add Styleguide NodeType

src/basic.ts, src/graph.ts, src/http-spec.ts, src/http.ts, src/servers.ts
Note that this targets "beta" branch, so we're relatively safe here in terms of changes, as beta isn't used anywhere _yet_.
=> feat: introduce IShareableNode

src/graph.ts
Came out of https://github.com/stoplightio/platform-internal/pull/11265#discussion_r866422353
=> feat: shareable INodeExternalExample

src/node.ts
Story: Display images kept in a private repository (https://github.com/stoplightio/platform-internal/issues/9997)
PR: https://github.com/stoplightio/platform-internal/pull/11603
I think we want analyzer to be able to understand Images in git projects and cli projects so we can deal with them appropriately (i.e. hash them and upload them to the user-images service as needed). These additional enum values are needed to make that happen, because the analyzer relies on `@stoplight/types`.
It's yalced in https://github.com/stoplightio/platform-internal/pull/11603
=> feat: add image types

src/http-spec.ts
=> feat: add internal to httpservice

src/node.ts
https://github.com/stoplightio/platform-internal/issues/11837
=> feat(node): add Javascript node format

src/http-spec.ts, src/node.ts
Adding to the existing callback type to fully support callbacks in http-spec, sldoc and oas3
=> feat: add to callback type

src/http-spec.ts
#15175
- add name as property on IHttpOperationRequestBody
- yalc'd it into platform-internal and verified it fixes my typing issues there
=> add name to IHttpOperationRequestBody

README.md
#InsertIssueNumberHere
last PR didn't have fix in the commit name so a new version wasn't released. Made readme changes to get the last PR's changes to release.
=> fix: release types

src/graph.ts
#15433
- adds id to INodeTag by extending IShareableNode
- http spec sets an id for Tags
=> INodeTag extends IShareableNode

README.md
=> fix: change readme to release types

src/node.ts
Needed by https://github.com/stoplightio/platform-internal/pull/15888
=> feat(node): add resolutions & override node types

src/graph.ts, src/http-spec.ts
* removes unused `unknownProperties`
* adds `explicitProperties` to param node for tracking
=> feat(http): remove unknownProps, add explicitProps to params

src/graph.ts, src/http-spec.ts
[platform-internal #15432](https://app.zenhub.com/workspaces/-team-tacocat-5eb9bc4a1fddfe30b94f78b1/issues/gh/stoplightio/platform-internal/15432)
Add `externalDocs` to services, operations, and tag definitions.
no tests added
=> feat: 15432 add externalDocs

src/http-spec.ts
[#17287](https://github.com/stoplightio/platform-internal/issues/17287)
- updates types to support callbacks in components and that they can be references
- yalc'd into http-spec and then into platform-internal, and those tests are passing
=> feat(http): add callbacks to components, tweak callback structure

src/graph.ts, src/http-spec.ts
Needed by https://github.com/stoplightio/platform-internal/pull/17626/
=> feat(http): add spec extensions to most of objects that may have it

src/http-spec.ts
adds unknown parameters as a tracked component
=> feat(oas): adds unknown parameters to track as components

src/http-spec.ts
adds info extensions to service since services may have its own.
=> feat(http): adds info extensions to service

src/http-spec.ts
adds the basic shape for oas 3.1 webhooks
=> feat(http): adds oas 3.1 webhooks to http types
